development:
  adapter: sqlite3
  database: db/clochette_dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/clochette_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/clochette.sqlite3
  pool: 5
  timeout: 5000
